# Generated by Django 4.2.2 on 2023-06-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_description_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(help_text="Enter an author's biography", max_length=1800),
        ),
    ]
